version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php
      - mysql
  php:
    image: php:7.4-fpm
    volumes:
      - ../:/var/www/html
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: zikaoMP
      MYSQL_USER: zikao
      MYSQL_PASSWORD: 123456

