version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - php
      - mysql
  php:
    image: php:7.4-fpm
    volumes:
      - .:/var/www/html
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - php
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: zikaoMP
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
